name: Schedule Edge Function

on:
  workflow_dispatch: # Allows manual triggering of the workflow for testing
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

jobs:
  trigger-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/functions/v1/check-expiring-documents" 
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" 
          -H "Content-Type: application/json"
