name: Schedule Edge Function

on:
  workflow_dispatch: # Allow manual triggering for testing
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC

jobs:
  trigger-function:
    runs-on: ubuntu-latest
    steps:
      - name: Print curl command for debugging
        run: |
          echo "curl -X POST '${{ secrets.SUPABASE_URL }}/functions/v1/check-expiring-documents' -H 'Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}' -H 'Content-Type: application/json'"

      - name: Call Supabase Edge Function
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/functions/v1/check-expiring-documents" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json"
