name: Schedule Edge Function

on:
  workflow_dispatch: # Allow manual triggering for testing
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC

jobs:
  trigger-function:
    runs-on: ubuntu-latest
    steps:
      - name: Print curl command for debugging
        run: |
          echo "Supabase URL: ${{ secrets.SUPABASE_URL }}"
          echo "Anon Key: ${{ secrets.SUPABASE_ANON_KEY }}"
